### PR TITLE
Initial sim sonar data function

### PR DESCRIPTION
**Pull request by romulogcerqueira**
Integration tests with vizkit3d_normal_depth_map. Created functions to set and simulate dynamic range control and sonar parameters (ad_interval, number_of_bins, motor_step_angle_size...), and rotate the sonar to obtain a 360 scanning image. Clear Code. It will be needed to syncronize the image rotating with scanning sonar rotating and improve the getPingIntensity() function.

### CODE REVIEW

**Comment by doudou** [comment]
General comment: you tried way too much to make the simulation look like a Tritech driver. This makes this code very quirky as you convert SI units to tritech-internal units for this purpose.

This is a scanning sonar simulator. Just define the parameters you can handle, and create your own configuration structure for those, using SI units. Even at the component level, the two components will have different parameters (if only because the simulator will never behave exactly like the real thing). The only thing that really matters is for the outputs to be the same.

**Comment by romulogcerqueira** [comment]
Hi, Sylvain.

Initially I agreed with Jan to use Tritech driver as a base. I think it is more feasible to test and validate the sonar simulation, using normal and depth informations, on a structure that receives real data, because we have to compare and evaluate its performance. After simulation validation, I will create its own configurable structure. What do you think?

**Comment by doudou** [comment]
You don't need to have the same fucked-up tritech-internal configuration parameters than tritech to compare the simulated data with the micron's real data. This is only understanding the configuration of the simulated sonar that much harder.

**Comment by romulogcerqueira** [comment]
I agree with you, Sylvain. I am refactoring my code and I will commit it soon.

Thanks for your help!

**Comment by romulogcerqueira** [comment]
The last update of this driver is in add_ping_pong_mode branch. So this pull request is being closed.

**Pull request closed without merging**
